// 幻雨喜欢小猫咪

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "GameplayTagContainer.h"

/**
 * 
 */
namespace TGameplayTags
{
	// 基础攻击技能
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack)
	// 按下普通攻击
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Pressed)
	// 释放普通攻击
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Released)
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo01)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo02)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo03)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_Combo04)
	// 旋风斩
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_CycloneSlashHold)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Change_End)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Damage)

	// 升龙拳
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Uppercut_Launch)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Uppercut_Cooldown)

	// 大地爆炸cd
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GroundBlast_Cooldown)
	// 击飞被动
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_Launch_Activate)

	// 射击
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot_Hand_l)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot_Hand_r)

	// 激光
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Laser_Shoot)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Laser_Cooldown)
	// 黑洞冷却
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BlackHole_Cooldown)
	
	// 冲刺
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Start)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Cooldown)

	// 龙卷风冷却
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Tornado_Cooldown)
	// 冻结冷却
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Freeze_Cooldown)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Blink_Teleport)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Blink_Cooldown)
	// 链式攻击
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChainAttack)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChainAttack_Cooldown)

	// 剑气
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SwordAura)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SwordAura_Cooldown)

	// ============ 大斧战士技能 ============
	// 战吼
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WarCry)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WarCry_Shout)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WarCry_Cooldown)
	// 断头台
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Guillotine)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Guillotine_Slam)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Guillotine_Cooldown)
	// 掷斧回旋
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AxeThrow)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AxeThrow_Release)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AxeThrow_Return)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AxeThrow_Cooldown)
	// 地裂
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earthquake)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earthquake_Slam1)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earthquake_Slam2)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earthquake_Slam3)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earthquake_Cooldown)

	// ============ 法师技能 ============
	// 奥术弹
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneOrb)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneOrb_Cast)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneOrb_Cooldown)
	// 相位转移
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PhaseShift)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PhaseShift_Shift)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PhaseShift_Cooldown)
	// 陨石打击
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_MeteorStrike)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_MeteorStrike_Impact)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_MeteorStrike_Cooldown)
	// 奥术风暴
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneStorm)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneStorm_Cooldown)

	
	// 通用技能伤害
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Generic_Damage)
	// 通用目标触发
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Generic_Target)
	
	// 状态
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats)
	// 死亡
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Dead)
	// 眩晕
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Stun)
	// 瞄准
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Aim)
	// 准星
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Crosshair)
	// 聚焦
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Focus)

	namespace Status
	{
		// 也是状态，以后的状态都放这里
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Phasing)
		// 冰冻标签
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Freeze)
		// 控制类
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Silence)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slow)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knockback)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knockup)
		
		// 生存类
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invisibility)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shield)
		
		// 持续伤害
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burn)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Poison)
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bleed)
		
		// 移动类
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Haste)
		
		// 特殊控制
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Taunt)
		
		// 免疫
		CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrowdControlImmunity)

	}
	//目标更新
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Updated)
	
	// 状态效果
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Debuff)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Buff)
	
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Health_Full)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Health_Empty)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Mana_Full)
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stats_Mana_Empty)
	

	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hero)


	// 经验
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeSet_Experience)
	// 金币
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeSet_Gold)

	// 伤害类型
	// 物理伤害
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_AttackDamage)
	// 魔法伤害
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_MagicDamage)
	// 真实伤害
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_TrueDamage)

	// 属性基础
	// 最大生命值
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth)
	// 当前生命值
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health)
	// 最大魔法值
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxMana)
	// 当前魔法值
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Mana)
	// 攻击力
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_AttackPower)
	// 魔法强度
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MagicPower)
	// 物抗
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Armor)
	// 魔抗
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MagicResistance)
	// 移动速度
	CRUNCH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MoveSpeed)
}